"""add pvz_city_code to seller_deliveries

Revision ID: 3ce89af7a4a8
Revises: add_is_test_mode
Create Date: 2026-03-12 21:56:06.260192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce89af7a4a8'
down_revision = 'add_is_test_mode'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pvz_city_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_deliveries', schema=None) as batch_op:
        batch_op.drop_column('pvz_city_code')

    # ### end Alembic commands ###
