"""Add updated_at to seller_deliveries

Revision ID: b6ddf6f76033
Revises: 000000000000
Create Date: 2026-03-09 22:43:55.133336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ddf6f76033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_deliveries', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
